---
- name: Create RHEL VM on OpenShift Virtualization
  hosts: localhost
  connection: local
  vars:
    vm_name: "{{disk_image}}-web-server"
    namespace: "default"
    storage_class: "ocs-storagecluster-ceph-rbd" # Change to your RWX storage class
    rhel_image: "quay.io/containerdisks/rhel:9-full" # Example RHEL container disk
    disk_image: rhel9
  tasks:
    - name: Create "{{ disk_image }}" VirtualMachine
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            annotations:
              kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1
            name: "{{vm_name}}"
            generation: 3
            namespace: "{{ namespace }}"
            finalizers:
              - kubevirt.io/virtualMachineControllerFinalize
            labels:
              app: "{{vm_name}}"
              kubevirt.io/dynamic-credentials-support: 'true'
              vm.kubevirt.io/template: "{{ disk_image }}-server-small"
              vm.kubevirt.io/template.namespace: openshift
              vm.kubevirt.io/template.revision: '1'
              vm.kubevirt.io/template.version: v0.32.2
          spec:
            dataVolumeTemplates:
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  name: "{{vm_name}}"
                spec:
                  sourceRef:
                    kind: DataSource
                    name: "{{ disk_image }}"
                    namespace: openshift-virtualization-os-images
                  storage:
                    resources:
                      requests:
                        storage: 30Gi
            running: true
            template:
              metadata:
                annotations:
                  vm.kubevirt.io/flavor: small
                  vm.kubevirt.io/os: "{{ disk_image }}"
                  vm.kubevirt.io/workload: server
                labels:
                  kubevirt.io/domain: "{{vm_name}}"
                  kubevirt.io/size: small
                  network.kubevirt.io/headlessService: headless
              spec:
                accessCredentials:
                  - sshPublicKey:
                      propagationMethod:
                        noCloud: {}
                      source:
                        secret:
                          secretName: nrathi-key
                architecture: amd64
                domain:
                  cpu:
                    cores: 1
                    sockets: 1
                    threads: 1
                  devices:
                    disks:
                      - disk:
                          bus: virtio
                        name: rootdisk
                      - disk:
                          bus: virtio
                        name: cloudinitdisk
                    interfaces:
                      - masquerade: {}
                        model: virtio
                        name: default
                    rng: {}
                  features:
                    acpi: {}
                    smm:
                      enabled: true
                  firmware:
                    bootloader:
                      efi: {}
                  machine:
                    type: pc-q35-rhel9.4.0
                  memory:
                    guest: 2Gi
                  resources: {}
                networks:
                  - name: default
                    pod: {}
                terminationGracePeriodSeconds: 180
                volumes:
                  - dataVolume:
                      name: "{{vm_name}}"
                    name: rootdisk
                  - cloudInitNoCloud:
                      userData: |-
                        #cloud-config
                        user: cloud-user
                        password: jacc-hqko-v4gf
                        chpasswd: { expire: False }
                    name: cloudinitdisk